import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Profile - View your Profile for AI-Interview platform",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
