import "../globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Authenticate to InterviewPrep",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
