"use client";

import "../globals.css";
// import { Metadata } from "next";
import { AuthProvider } from "@/context/auth.context";
import { AppSidebar } from "@/components/layout/sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

// export const metadata: Metadata = {
//   title: "Dashboard - View Your AI-Interviews",
//   description: "Generated by create next app",
// };

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <SidebarProvider>
        <div className="flex min-h-screen bg-gray-50 w-full">
          <AppSidebar />
          <main className="flex-1 relative w-full max-w-[1200px] mx-auto">
            <SidebarTrigger />
            {children}
          </main>
        </div>
      </SidebarProvider>
    </AuthProvider>
  );
}
