import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Interviews - View Personal or Custom AI-Interviews",
  description: "Generated by create next app",
};

export default function InterviewLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
