"use client";

import "../globals.css";
// import { Metadata } from "next";
import { AuthProvider } from "@/context/auth.context";

// export const metadata: Metadata = {
//   title: "Profile Onboarding - Complete your profile",
//   description: "Generated by create next app",
// };

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <AuthProvider>{children}</AuthProvider>
    </main>
  );
}
